apiVersion: v1
kind: Pod
metadata:
  name: explorer
spec:
  containers:
    - name: explorer
      image: registry.k8s.io/explorer:1.0
      args: ["-port=8080"]
      ports:
        - containerPort: 8080
          protocol: TCP
      volumeMounts:
        - mountPath: "/mount/test-volume"
          name: test-volume
  volumes:
    - name: test-volume
      emptyDir: {}
