apiVersion: v1
kind: Pod
metadata:
  name: test-portworx-volume-pod
spec:
  containers:
  - image: registry.k8s.io/test-webserver
    name: test-container
    volumeMounts:
    - mountPath: /test-portworx-volume
      name: test-volume
  volumes:
  - name: test-volume
    # This Portworx volume must already exist.
    portworxVolume:
      volumeID: "vol1"
